version: "3.8"
services:
  backend:
    build: ./backend
    container_name: api_jenkins
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo:27017/miapp

  frontend:
    build: ./frontend
    container_name: web_jenkins
    ports:
      - "8081:80"
    depends_on:
      - backend

  mongo:
    image: mongo
    container_name: mongo_jenkins
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
